name: gemini_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  bloc: ^8.1.4
  cloud_firestore: ^5.1.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  firebase_auth: ^5.1.2
  firebase_core: ^3.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  formz: ^0.7.0
  get_it: ^7.7.0
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  hydrated_bloc: ^9.1.5
  json_annotation: ^4.9.0
  path_provider: ^2.1.3
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.4.1
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  test: ^1.25.2

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#F6F5F0"
  color_dark: "#272726"
  image: assets/gemini-logo.png
  branding: assets/gemini-name.png
  branding_mode: bottom
  android_12:
    image: assets/gemini-logo.png
    branding: assets/gemini-name.png
    branding_mode: bottom
    color: "#F6F5F0"
    color_dark: "#272726"