// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdFj2oFQg9TaWV5V-U9zWNFG3Osu1fFTE',
    appId: '1:415577495058:web:cd64449fee59c7adad2acb',
    messagingSenderId: '415577495058',
    projectId: 'gemini-app-3b9f7',
    authDomain: 'gemini-app-3b9f7.firebaseapp.com',
    storageBucket: 'gemini-app-3b9f7.appspot.com',
    measurementId: 'G-97T58Y6PPK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApeitnpG-cEu-j-JisIjUgxKhwelFJbzc',
    appId: '1:415577495058:android:8942d2f9e51cec77ad2acb',
    messagingSenderId: '415577495058',
    projectId: 'gemini-app-3b9f7',
    storageBucket: 'gemini-app-3b9f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEWu3dVrunHWk2qPbSYEDsaUEVMjnCLMM',
    appId: '1:415577495058:ios:603737c318631a33ad2acb',
    messagingSenderId: '415577495058',
    projectId: 'gemini-app-3b9f7',
    storageBucket: 'gemini-app-3b9f7.appspot.com',
    iosBundleId: 'com.example.geminiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEWu3dVrunHWk2qPbSYEDsaUEVMjnCLMM',
    appId: '1:415577495058:ios:603737c318631a33ad2acb',
    messagingSenderId: '415577495058',
    projectId: 'gemini-app-3b9f7',
    storageBucket: 'gemini-app-3b9f7.appspot.com',
    iosBundleId: 'com.example.geminiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdFj2oFQg9TaWV5V-U9zWNFG3Osu1fFTE',
    appId: '1:415577495058:web:1103a91ae67d21eead2acb',
    messagingSenderId: '415577495058',
    projectId: 'gemini-app-3b9f7',
    authDomain: 'gemini-app-3b9f7.firebaseapp.com',
    storageBucket: 'gemini-app-3b9f7.appspot.com',
    measurementId: 'G-9KZVM9KXL5',
  );
}
